// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solvedPuzzle.proto

public final class SolvedPuzzle {
  private SolvedPuzzle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PuzzleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Puzzle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string puzzle = 1;</code>
     */
    java.lang.String getPuzzle();
    /**
     * <code>optional string puzzle = 1;</code>
     */
    com.google.protobuf.ByteString
        getPuzzleBytes();
  }
  /**
   * Protobuf type {@code Puzzle}
   */
  public  static final class Puzzle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Puzzle)
      PuzzleOrBuilder {
    // Use Puzzle.newBuilder() to construct.
    private Puzzle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Puzzle() {
      puzzle_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Puzzle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              puzzle_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SolvedPuzzle.internal_static_Puzzle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SolvedPuzzle.internal_static_Puzzle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SolvedPuzzle.Puzzle.class, SolvedPuzzle.Puzzle.Builder.class);
    }

    public static final int PUZZLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object puzzle_;
    /**
     * <code>optional string puzzle = 1;</code>
     */
    public java.lang.String getPuzzle() {
      java.lang.Object ref = puzzle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        puzzle_ = s;
        return s;
      }
    }
    /**
     * <code>optional string puzzle = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPuzzleBytes() {
      java.lang.Object ref = puzzle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        puzzle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPuzzleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, puzzle_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPuzzleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, puzzle_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SolvedPuzzle.Puzzle)) {
        return super.equals(obj);
      }
      SolvedPuzzle.Puzzle other = (SolvedPuzzle.Puzzle) obj;

      boolean result = true;
      result = result && getPuzzle()
          .equals(other.getPuzzle());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PUZZLE_FIELD_NUMBER;
      hash = (53 * hash) + getPuzzle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SolvedPuzzle.Puzzle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SolvedPuzzle.Puzzle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SolvedPuzzle.Puzzle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SolvedPuzzle.Puzzle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SolvedPuzzle.Puzzle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SolvedPuzzle.Puzzle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SolvedPuzzle.Puzzle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SolvedPuzzle.Puzzle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SolvedPuzzle.Puzzle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SolvedPuzzle.Puzzle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SolvedPuzzle.Puzzle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Puzzle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Puzzle)
        SolvedPuzzle.PuzzleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SolvedPuzzle.internal_static_Puzzle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SolvedPuzzle.internal_static_Puzzle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SolvedPuzzle.Puzzle.class, SolvedPuzzle.Puzzle.Builder.class);
      }

      // Construct using SolvedPuzzle.Puzzle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        puzzle_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SolvedPuzzle.internal_static_Puzzle_descriptor;
      }

      public SolvedPuzzle.Puzzle getDefaultInstanceForType() {
        return SolvedPuzzle.Puzzle.getDefaultInstance();
      }

      public SolvedPuzzle.Puzzle build() {
        SolvedPuzzle.Puzzle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SolvedPuzzle.Puzzle buildPartial() {
        SolvedPuzzle.Puzzle result = new SolvedPuzzle.Puzzle(this);
        result.puzzle_ = puzzle_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SolvedPuzzle.Puzzle) {
          return mergeFrom((SolvedPuzzle.Puzzle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SolvedPuzzle.Puzzle other) {
        if (other == SolvedPuzzle.Puzzle.getDefaultInstance()) return this;
        if (!other.getPuzzle().isEmpty()) {
          puzzle_ = other.puzzle_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SolvedPuzzle.Puzzle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SolvedPuzzle.Puzzle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object puzzle_ = "";
      /**
       * <code>optional string puzzle = 1;</code>
       */
      public java.lang.String getPuzzle() {
        java.lang.Object ref = puzzle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          puzzle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string puzzle = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPuzzleBytes() {
        java.lang.Object ref = puzzle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          puzzle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string puzzle = 1;</code>
       */
      public Builder setPuzzle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        puzzle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string puzzle = 1;</code>
       */
      public Builder clearPuzzle() {
        
        puzzle_ = getDefaultInstance().getPuzzle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string puzzle = 1;</code>
       */
      public Builder setPuzzleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        puzzle_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Puzzle)
    }

    // @@protoc_insertion_point(class_scope:Puzzle)
    private static final SolvedPuzzle.Puzzle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SolvedPuzzle.Puzzle();
    }

    public static SolvedPuzzle.Puzzle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Puzzle>
        PARSER = new com.google.protobuf.AbstractParser<Puzzle>() {
      public Puzzle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Puzzle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Puzzle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Puzzle> getParserForType() {
      return PARSER;
    }

    public SolvedPuzzle.Puzzle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Puzzle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Puzzle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022solvedPuzzle.proto\"\030\n\006Puzzle\022\016\n\006puzzle" +
      "\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Puzzle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Puzzle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Puzzle_descriptor,
        new java.lang.String[] { "Puzzle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
